UPDATE devices set dev_accn='LN' where dev_id ='BF82E0';
UPDATE devices set dev_accn='DF' where dev_id ='C3094C';
UPDATE devices set dev_accn='JB' where dev_id ='BF920C';
UPDATE devices set dev_accn='LOT' where dev_id ='C30A84';
UPDATE devices set dev_accn='Y' where dev_id ='C308B0';
UPDATE devices set dev_accn='ENW' where dev_id ='C307BC';
UPDATE devices set dev_accn='212' where dev_id ='C3079C';
UPDATE devices set dev_accn='325' where dev_id ='BF9074';
UPDATE devices set dev_accn='302' where dev_id ='C30A24';
